version: 2

models:
  - name: customers
    description: A final table

    columns:
        - name: customer_id
          description: This is a unique identifier for the customer
          tests:
              - unique
              - not_null
        - name: first_name
          description: First name
          tests:
              - not_null
        - name: last_name
          description: Last name
          tests:
              - not_null